# Example GitHub Actions workflows for different static site generators

# ============================================================================
# Option 1: MkDocs Material
# ============================================================================
name: Deploy MkDocs
on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
      
      - name: Build and deploy
        run: mkdocs gh-deploy --force

# ============================================================================
# Option 2: Hugo
# ============================================================================
# name: Deploy Hugo
# on:
#   push:
#     branches: [master]
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true  # Fetch Hugo themes
#       
#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: 'latest'
#           extended: true
#       
#       - name: Build
#         run: hugo --minify
#       
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public

# ============================================================================
# Option 3: Docusaurus
# ============================================================================
# name: Deploy Docusaurus
# on:
#   push:
#     branches: [master]
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: npm
#       
#       - name: Install dependencies
#         run: npm ci
#       
#       - name: Build
#         run: npm run build
#       
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./build

# ============================================================================
# Option 4: VitePress
# ============================================================================
# name: Deploy VitePress
# on:
#   push:
#     branches: [master]
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       
#       - name: Install dependencies
#         run: npm install
#       
#       - name: Build
#         run: npm run docs:build
#       
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: docs/.vitepress/dist

# ============================================================================
# Option 5: Sphinx (Python docs)
# ============================================================================
# name: Deploy Sphinx
# on:
#   push:
#     branches: [master]
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.x
#       
#       - name: Install Sphinx
#         run: |
#           pip install sphinx sphinx-rtd-theme
#       
#       - name: Build
#         run: |
#           cd docs
#           make html
#       
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: docs/_build/html


